In [20]:
%load_ext autoreload

%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
import numpy as np
from mlp.layers import *
from scipy import signal
inputs = np.arange(2*3*8**2).reshape((2, 3, 8, 8))
inputs

array([[[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31],
         [ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]],

        [[ 64,  65,  66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87],
         [ 88,  89,  90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111],
         [112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127]],

        [[128, 129, 130, 131, 132, 133, 134, 135],
         [136, 137, 138, 139, 140, 141, 142, 143],
         [144, 145, 146, 147, 148, 149, 150, 151],
         [152, 153, 154, 15

In [68]:
layer = MaxPoolingLayer()
a = layer.fprop(inputs)
print(a)
print( a.shape)

[[[[   9.   11.   13.   15.]
   [  25.   27.   29.   31.]
   [  41.   43.   45.   47.]
   [  57.   59.   61.   63.]]

  [[  73.   75.   77.   79.]
   [  89.   91.   93.   95.]
   [ 105.  107.  109.  111.]
   [ 121.  123.  125.  127.]]

  [[ 137.  139.  141.  143.]
   [ 153.  155.  157.  159.]
   [ 169.  171.  173.  175.]
   [ 185.  187.  189.  191.]]]


 [[[ 201.  203.  205.  207.]
   [ 217.  219.  221.  223.]
   [ 233.  235.  237.  239.]
   [ 249.  251.  253.  255.]]

  [[ 265.  267.  269.  271.]
   [ 281.  283.  285.  287.]
   [ 297.  299.  301.  303.]
   [ 313.  315.  317.  319.]]

  [[ 329.  331.  333.  335.]
   [ 345.  347.  349.  351.]
   [ 361.  363.  365.  367.]
   [ 377.  379.  381.  383.]]]]
(2, 3, 4, 4)
